Update gradle.properties
tomblachut/svelte-intellij pull request #291
Opened 2022-05-24 06:54 UTC by martinbeentjes

Currently JetBrains is running a closed beta with the new UI design. I would like to have the latest EAP to support the plugin. I do not know if it will work, reading from the docs this should do the trick from the side of IDEA telling it is supported.

2022-05-24 13:44 UTC, tomblachut requested changes

2022-05-24 13:44 UTC, tomblachut commented on src/main/java/dev/blachut/svelte/lang/codeInsight/SvelteComponentCandidatesProvider.kt
> +    override fun getNames(keyFilter: Predicate<in String>): MutableSet<String> {
Why did you change `Set` into `MutableSet`?

2022-05-24 13:44 UTC, tomblachut commented on build.gradle.kts
> +    val javaVersion = "17"
Please don't change more than necessary, let's stay on Java 11 & Kotlin 1.5 for maximum compatibility

2022-05-24 13:44 UTC, tomblachut commented on src/main/java/dev/blachut/svelte/lang/codeInsight/SvelteKitModuleReferenceContributor.kt
> +        val index = ProjectFileIndex.getInstance(mutableContext.project)
This change are irrelevant too. It pollutes git history for no tangible gain 😕

2022-05-24 14:24 UTC, martinbeentjes commented on src/main/java/dev/blachut/svelte/lang/completion/SvelteAttributeValueCompletionProvider.kt
> -                result.add(it.displayName.toLowerCase(Locale.US))
This was a deprecation warning.

2022-05-24 14:25 UTC, martinbeentjes commented on src/main/java/dev/blachut/svelte/lang/codeInsight/SvelteComponentCandidatesProvider.kt
> -    override fun getNames(keyFilter: Predicate<String>): Set<String> {
This was necessary to fix the 'getNames overrides nothing' error.

2022-05-24 14:25 UTC, martinbeentjes commented
@tomblachut I've fixed the mentioned issues.

2022-05-25 14:49 UTC, tomblachut approved these changes

2022-05-25 14:50 UTC, merged

2022-05-25 14:50 UTC, tomblachut commented
@martinbeentjes thanks again for the contribution!